### ISSUE TITLE
Samsung S9+ (Android 9) dont work 

### ISSUE THREAD

**Issue by MickLesk** [JimmyPun610/Plugin.XF.TouchID#1]
Ive not found the error, but with the Samsung S9+ (Android 9 API 28) the Dialog / Authentificator dont show. App Build, but the button dont work.

**Comment by JimmyPun610** [comment]
Is there any error message?

**Comment by MickLesk** [comment]
No i dont see any error, with debugger it dont run on any exception.

**Comment by JimmyPun610** [comment]
Seem something went wrong on using secret key on android 9.0.
Please update to v1.1.0.3 for Android 9 implementation.
Please noted that some configuration is required after you upgrade it.
1. Android Target Framework switch to Android 9
2. Update the Manifest, please refer to readme.md
3. Set IsUseSecretKey to false if necessary.

Please close it if the issue if solved

**Comment by MickLesk** [comment]
Hey Jimmy,

that's look good!
The issue with Android 9.0 is fixed.

Thanks :-)
